#ifndef BEDROCK_SERVER_WINDOWS_H
#define BEDROCK_SERVER_WINDOWS_H

enum
{
	WINDOW_INVENTORY,

	WINDOW_CHEST = 0
};

enum
{
	INVENTORY_CRAFT_OUTPUT,
	INVENTOTY_CRAFT_START,
	INVENTORY_CRAFT_END = 4,
	INVENTORY_HELM,
	INVENTORY_TOP,
	INVENTORY_LEGS,
	INVENTORY_BOOTS,
	INVENTORY_START = 9,
	INVENTORY_HOTBAR_START = 36,
	INVENTORY_SIZE = 44,

	INVENTORY_HOTBAR_SIZE = 9
};

enum
{
	CHEST_CHEST_START = 0,
	CHEST_INVENTORY_START = 27,
	CHEST_HOTBAR_START = 54,
	CHEST_SIZE = 63
};

#endif // BEDROCK_SERVER_WINDOWS_H
