
typedef enum
{
	BLOCK_AIR,                   /* 0 */
	BLOCK_STONE,                 /* 1 */
	BLOCK_GRASS,                 /* 2 */
	BLOCK_DIRT,                  /* 3 */
	BLOCK_COBBLESTONE,           /* 4 */
	BLOCK_WOODEN_PLANKS,         /* 5 */
	BLOCK_SAPLINGS,              /* 6 */
	BLOCK_BEDROCK,               /* 7 */
	BLOCK_WATER,                 /* 8 */
	BLOCK_STATIONARY_WATER,      /* 9 */
	BLOCK_LAVA,                  /* 10 */
	BLOCK_STSATIONARY_LAVA,      /* 11 */
	BLOCK_SAND,                  /* 12 */
	BLOCK_GRAVEL,                /* 13 */
	BLOCK_GOLD_ORE,              /* 14 */
	BLOCK_IRON_ORE,              /* 15 */
	BLOCK_COAL_ORE,              /* 16 */
	BLOCK_WOOD,                  /* 17 */
	BLOCK_LEAVES,                /* 18 */
	BLOCK_SPONGE,                /* 19 */
	BLOCK_GLASS,                 /* 20 */
	BLOCK_LAPIS_LAZULI_ORE,      /* 21 */
	BLOCK_LAPIS_LAZULI_BLOCK,    /* 22 */
	BLOCK_DISPENSER,             /* 23 */
	BLOCK_SANDSTONE,             /* 24 */
	BLOCK_NOTE_BLOCK,            /* 25 */
	BLOCK_BED,                   /* 26 */
	BLOCK_POWERED_RAIL,          /* 27 */
	BLOCK_DETECTOR_RAIL,         /* 28 */
	BLOCK_STICKY_PISTON,         /* 29 */
	BLOCK_COBWEB,                /* 30 */
	BLOCK_TALL_GRASS,            /* 31 */
	BLOCK_DEAD_BUSH,             /* 32 */
	BLOCK_PISTON,                /* 33 */
	BLOCK_PISTON_EXTENSION,      /* 34 */
	BLOCK_WOOL,                  /* 35 */
	BLOCK_MOVED_BY_PISTON,       /* 36 */
	BLOCK_DANDELION,             /* 37 */
	BLOCK_ROSE,                  /* 38 */
	BLOCK_BROWN_MUSHROOM,        /* 39 */
	BLOCK_RED_MUSHROOM,          /* 40 */
	BLOCK_OF_GOLD,               /* 41 */
	BLOCK_OF_IRON,               /* 42 */
	BLOCK_DOUBLE_SLABS,          /* 43 */
	BLOCK_SLABS,                 /* 44 */
	BLOCK_BRICKS,                /* 45 */
	BLOCK_TNT,                   /* 46 */
	BLOCK_BOOKSHELF,             /* 47 */
	BLOCK_MOSS_STONE,            /* 48 */
	BLOCK_OBSIDIAN,              /* 49 */
	BLOCK_TORCH,                 /* 50 */
	BLOCK_FIRE,                  /* 51 */
	BLOCK_MONSTER_SPAWNER,       /* 52 */
	BLOCK_WOODEN_STAIRS,         /* 53 */
	BLOCK_CHEST,                 /* 54 */
	BLOCK_REDSTONE_WIRE,         /* 55 */
	BLOCK_DIAMOND_ORE,           /* 56 */
	BLOCK_DIAMOND,               /* 57 */
	BLOCK_CRAFTING_TABLE,        /* 58 */
	BLOCK_WHEAT_SEEDS,           /* 59 */
	BLOCK_FARMLAND,              /* 60 */
	BLOCK_FURNACE,               /* 61 */
	BLOCK_BURNING_FURNACE,       /* 62 */
	BLOCK_SIGN_POST,             /* 63 */
	BLOCK_WOODEN_DOOR,           /* 64 */
	BLOCK_LADDERS,               /* 65 */
	BLOCK_RAILS,                 /* 66 */
	BLOCK_COBBLESTONE_STAIRS,    /* 67 */
	BLOCK_WALL_SIGN,             /* 68 */
	BLOCK_LEVER,                 /* 69 */
	BLOCK_STONE_PRESSURE_PLATE,  /* 70 */
	BLOCK_IRON_DOOR,             /* 71 */
	BLOCK_WOODEN_PRESSURE_PLATE, /* 72 */
	BLOCK_REDSTONE_ORE,          /* 73 */
	BLOCK_GLOWING_REDSTONE_ORE,  /* 74 */
	BLOCK_REDSTONE_TORCH_OFF,    /* 75 */
	BLOCK_REDSTONE_TORCH_ON,     /* 76 */
	BLOCK_STONE_BUTTON,          /* 77 */
	BLOCK_SNOW,                  /* 78 */
	BLOCK_ICE,                   /* 79 */
	BLOCK_SNOW_BLOCK,            /* 80 */
	BLOCK_CACTUS,                /* 81 */
	BLOCK_CLAY_BLOCK,            /* 82 */
	BLOCK_SUGAR_CANE,            /* 83 */
	BLOCK_JUKEBOX,               /* 84 */
	BLOCK_FENCE,                 /* 85 */
	BLOCK_PUMPKIN,               /* 86 */
	BLOCK_NETHERRACK,            /* 87 */
	BLOCK_SOUL_SAND,             /* 88 */
	BLOCK_GLOWSTONE_BLOCK,       /* 89 */
	BLOCK_PORTAL,                /* 90 */
	BLOCK_JACK_O_LANTERN,        /* 91 */
	BLOCK_CAKE_BLOCK,            /* 92 */
	BLOCK_REDSTONE_REPEATER_OFF, /* 93 */
	BLOCK_REDSTONE_REPEATER_ON,  /* 94 */
	BLOCK_LOCKED_CHEST,          /* 95 */
	BLOCK_TRAPDOOR,              /* 96 */
	BLOCK_MONSTER_EGG,           /* 97 */
	BLOCK_STONE_BRICKS,          /* 98 */
	BLOCK_HUGE_BROWN_MUSHROOM,   /* 99 */
	BLOCK_HUGE_RED_MUSHROOM,     /* 100 */
	BLOCK_IRON_BARS,             /* 101 */
	BLOCK_GLASS_PANE,            /* 102 */
	BLOCK_MELON,                 /* 103 */
	BLOCK_PUMPKIN_STEM,          /* 104 */
	BLOCK_MELON_STEM,            /* 105 */
	BLOCK_VINES,                 /* 106 */
	BLOCK_FENCED_GATE,           /* 107 */
	BLOCK_BRICK_STAIRS,          /* 108 */
	BLOCK_STONE_BRICK_STAIRS,    /* 109 */
	BLOCK_MYCELIUM,              /* 110 */
	BLOCK_LILY_PAD,              /* 111 */
	BLOCK_NETHER_BRICK,          /* 112 */
	BLOCK_NETHER_BRICK_FENCE,    /* 113 */
	BLOCK_NETHER_BRICK_STAIRS,   /* 114 */
	BLOCK_NETHER_WART,           /* 115 */
	BLOCK_ENCHANTMENT_TABLE,     /* 116 */
	BLOCK_BREWING_STAND,         /* 117 */
	BLOCK_CAULDRON,              /* 118 */
	BLOCK_END_PORTAL,            /* 119 */
	BLOCK_END_PORTAL_FRAME,      /* 120 */
	BLOCK_END_STONE,             /* 121 */
	BLOCK_DRAGON_EGG,            /* 122 */
	BLOCK_REDSTONE_LAMP_OFF,     /* 123 */
	BLOCK_REDSTONE_LAMP_ON,      /* 124 */
	BLOCK_WOODEN_DOUBLE_SLAB,    /* 125 */
	BLOCK_WOODEN_SLAB,           /* 126 */
	BLOCK_COCOA_PLANT,           /* 127 */
	BLOCK_SANDSTONE_STAIRS,      /* 128 */
	BLOCK_EMERALD_ORE,           /* 129 */
	BLOCK_ENDER_CHEST            /* 130 */
} block_type;

typedef enum
{
	ITEM_IRON_SHOVEL = 256,      /* 256 */
	ITEM_IRON_PICKAXE,           /* 257 */
	ITEM_IRON_AXE,               /* 258 */
	ITEM_FLINT_AND_STEEL,        /* 259 */
	ITEM_RED_APPLE,              /* 260 */
	ITEM_BOW,                    /* 261 */
	ITEM_ARROW,                  /* 262 */
	ITEM_COAL,                   /* 263 */
	ITEM_DIAMOND,                /* 264 */
	ITEM_IRON_INGOT,             /* 265 */
	ITEM_GOLD_INGOT,             /* 266 */
	ITEM_IRON_SWORD,             /* 267 */
	ITEM_WOODEN_SWORD,           /* 268 */
	ITEM_WOODEN_SHOVEL,          /* 269 */
	ITEM_WOODEN_PICKAXE,         /* 270 */
	ITEM_WOODEN_AXE,             /* 271 */
	ITEM_STONE_SWORD,            /* 272 */
	ITEM_STONE_SHOVEL,           /* 273 */
	ITEM_STONE_PICKAXE,          /* 274 */
	ITEM_STONE_AXE,              /* 275 */
	ITEM_DIAMOND_SWORD,          /* 276 */
	ITEM_DIAMOND_SHOVEL,         /* 277 */
	ITEM_DIAMOND_PICKAXE,        /* 278 */
	ITEM_DIAMOND_AXE,            /* 279 */
	ITEM_STICK,                  /* 280 */
	ITEM_BOWL,                   /* 281 */
	ITEM_MUSHROOM_SOUP,          /* 282 */
	ITEM_GOLD_SWORD,             /* 283 */
	ITEM_GOLD_SHOVEL,            /* 284 */
	ITEM_GOLD_PICKAXE,           /* 285 */
	ITEM_GOLD_AXE,               /* 286 */
	ITEM_STRING,                 /* 287 */
	ITEM_FEATHER,                /* 288 */
	ITEM_GUNPOWDER,              /* 289 */
	ITEM_WOODEN_HOE,             /* 290 */
	ITEM_STONE_HOE,              /* 291 */
	ITEM_IRON_HOE,               /* 292 */
	ITEM_DIAMOND_HOE,            /* 293 */
	ITEM_GOLD_HOE,               /* 294 */
	ITEM_SEEDS,                  /* 295 */
	ITEM_WHEAT,                  /* 296 */
	ITEM_BREAD,                  /* 297 */
	ITEM_LEATHER_CAP,            /* 298 */
	ITEM_LEATHER_TUNIC,          /* 299 */
	ITEM_LEATHER_PANTS,          /* 300 */
	ITEM_LEATHER_BOOTS,          /* 301 */
	ITEM_CHAIN_HELMET,           /* 302 */
	ITEM_CHAIN_CHESTPLATE,       /* 303 */
	ITEM_CHAIN_LEGGINGS,         /* 304 */
	ITEM_CHAIN_BOOTS,            /* 305 */
	ITEM_IRON_HELMET,            /* 306 */
	ITEM_IRON_CHESTPLATE,        /* 307 */
	ITEM_IRON_LEGGINGS,          /* 308 */
	ITEM_IRON_BOOTS,             /* 309 */
	ITEM_DIAMOND_HELMET,         /* 310 */
	ITEM_DIAMOND_CHESTPLATE,     /* 311 */
	ITEM_DIAMOND_LEGGINGS,       /* 312 */
	ITEM_DIAMOND_BOOTS,          /* 313 */
	ITEM_GOLDEN_HELMET,          /* 314 */
	ITEM_GOLDEN_CHESTPLATE,      /* 315 */
	ITEM_GOLDEN_LEGGINGS,        /* 316 */
	ITEM_GOLDEN_BOOTS,           /* 317 */
	ITEM_FLINT,                  /* 318 */
	ITEM_RAW_PORKCHOP,           /* 319 */
	ITEM_COOKED_PORKCHOP,        /* 320 */
	ITEM_PAINTINGS,              /* 321 */
	ITEM_GOLDEN_APPLE,           /* 322 */
	ITEM_SIGN,                   /* 323 */
	ITEM_WOODEN_DOOR,            /* 324 */
	ITEM_BUCKET,                 /* 325 */
	ITEM_WATER_BUCKET,           /* 326 */
	ITEM_LAVA_BUCKET,            /* 327 */
	ITEM_MINECART,               /* 328 */
	ITEM_SADDLE,                 /* 329 */
	ITEM_IRON_DOOR,              /* 330 */
	ITEM_REDSTONE_DUST,          /* 331 */
	ITEM_SNOWBALL,               /* 332 */
	ITEM_BOAT,                   /* 333 */
	ITEM_LEATHER,                /* 334 */
	ITEM_MILK_BUCKET,            /* 335 */
	ITEM_CLAY_BRICK,             /* 336 */
	ITEM_CLAY,                   /* 337 */
	ITEM_SUGAR_CANE,             /* 338 */
	ITEM_PAPER,                  /* 339 */
	ITEM_BOOK,                   /* 340 */
	ITEM_SLIMEBALL,              /* 341 */
	ITEM_MINECRAFT_WITH_CHEST,   /* 342 */
	ITEM_MINECRAFT_WITH_FURNACE, /* 343 */
	ITEM_CHICKEN_EGG,            /* 344 */
	ITEM_COMPASS,                /* 345 */
	ITEM_FISHING_ROD,            /* 346 */
	ITEM_CLOCK,                  /* 347 */
	ITEM_GLOWSTONE_DUST,         /* 348 */
	ITEM_RAW_FISH,               /* 349 */
	ITEM_COOKED_FISH,            /* 350 */
	ITEM_DYE,                    /* 351 */
	ITEM_BONE,                   /* 352 */
	ITEM_SUGAR,                  /* 353 */
	ITEM_CAKE,                   /* 354 */
	ITEM_BED,                    /* 355 */
	ITEM_REDSTONE_REPEATER,      /* 356 */
	ITEM_COOKIE,                 /* 357 */
	ITEM_MAP,                    /* 358 */
	ITEM_SHEARS,                 /* 359 */
	ITEM_MELON_SLICE,            /* 360 */
	ITEM_PUMPKIN_SEEDS,          /* 361 */
	ITEM_MELON_SEEDS,            /* 362 */
	ITEM_RAW_BEEF,               /* 363 */
	ITEM_STEAK,                  /* 364 */
	ITEM_RAW_CHICKEN,            /* 365 */
	ITEM_COOKED_CHICKEN,         /* 366 */
	ITEM_ROTTEN_FLESH,           /* 367 */
	ITEM_ENDER_PEARL,            /* 368 */
	ITEM_BLAZE_ROD,              /* 369 */
	ITEM_GHAST_TEAR,             /* 370 */
	ITEM_GOLD_NUGGET,            /* 371 */
	ITEM_NETHER_WART,            /* 372 */
	ITEM_POTIONS,                /* 373 */
	ITEM_GLASS_BOTTLE,           /* 374 */
	ITEM_SPIDER_EYE,             /* 375 */
	ITEM_FERMENTED_SPIDER_EYE,   /* 376 */
	ITEM_BLAZE_POWDER,           /* 377 */
	ITEM_MAGMA_CREAM,            /* 378 */
	ITEM_BREWING_STAND,          /* 379 */
	ITEM_CAULDRON,               /* 380 */
	ITEM_EYE_OF_ENDER,           /* 381 */
	ITEM_GLISTERING_MELON,       /* 382 */
	ITEM_SPAWN_EGG,              /* 383 */
	ITEM_BOTTLE_OF_ENCHANTING,   /* 384 */
	ITEM_FIRE_CHARGE,            /* 385 */
	ITEM_BOOK_AND_QUILL,         /* 386 */
	ITEM_WRITTEN_BOOK,           /* 387 */
	ITEM_EMERALD,                /* 388 */
	ITEM_13_DISC = 2256,         /* 2256 */
	ITEM_CAT_DISC,               /* 2257 */
	ITEM_BLOCKS_DISC,            /* 2258 */
	ITEM_CHIRP_DISC,             /* 2259 */
	ITEM_FAR_DISC,               /* 2260 */
	ITEM_MALL_DISC,              /* 2261 */
	ITEM_MELLOHI_DISC,           /* 2262 */
	ITEM_STAL_DISC,              /* 2263 */
	ITEM_STRAD_DISC,             /* 2264 */
	ITEM_WARD_DISC,              /* 2265 */
	ITEM_11_DISC                 /* 2266 */
} item_type;
